#!/usr/bin/env bash
# Apply the requested IORM plan on cell fra131885exdcl02.
#
# Run this script locally on the cell as a CellCLI-authorized account
# (normally root or celladmin).  The IORM plan object's name is generated by
# CellCLI as <cell-name>_IORMPLAN; it is not created with a user-selected name.
#
# IMPORTANT: dbPlan and clusterPlan are complete plan attributes.  This replaces
# the current database directives and clears any existing cluster directives.

set -euo pipefail

readonly EXPECTED_PLAN='fra131885exdcl02_IORMPLAN'
readonly IORM_COMMAND='alter iormplan dbplan=((name=OECSN1EXA,share=2,flashCacheMin=18T),(name=OECSN3PAC,share=2),(name=OECSN4CTM,share=1),(name=OECSN5SAT,share=1),(name=default,share=1)),clusterplan="",objective=auto'

command -v cellcli >/dev/null 2>&1 || {
  echo 'ERROR: cellcli is not in PATH. Run this on the storage cell.' >&2
  exit 1
}

actual_plan="$(cellcli -e 'list iormplan attributes name' | tr -d '[:space:]')"
if [[ "$actual_plan" != "$EXPECTED_PLAN" ]]; then
  echo "ERROR: expected IORM plan $EXPECTED_PLAN, found ${actual_plan:-<none>}." >&2
  echo 'Run this script on fra131885exdcl02, or change EXPECTED_PLAN after verifying the target cell.' >&2
  exit 1
fi

echo 'Current IORM plan (backup this output before proceeding):'
cellcli -e 'list iormplan detail'

echo
echo 'Flash cache capacity (18T is reserved on this cell for OECSN1EXA):'
cellcli -e 'list flashcache attributes size'

read -r -p 'Apply the requested IORM plan? [y/N] ' confirmation
if [[ "$confirmation" != 'y' && "$confirmation" != 'Y' ]]; then
  echo 'No changes made.'
  exit 0
fi

cellcli -e "$IORM_COMMAND"

echo
echo 'Applied IORM plan:'
cellcli -e 'list iormplan detail'
